version: '3.9'

services:
  go:
    build: ./go
    environment:
      - MYSQL_DSN=root:password@tcp(db:3306)/sample?charset=utf8mb4&parseTime=True&loc=Local
    volumes:
      - ./go:/var/www/go:cached
      - ./api:/var/www/api:cached
      - /var/www/go/tmp
    ports:
      - "${GO_PORT:-50051}:50051"
    command: tail -f /dev/null

  nextjs:
    build: ./nextjs
    environment:
      - GRPC_HOST=go
      - BINDING=0.0.0.0
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7-debian
    networks:
      - default
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
      - TZ=Asia/Tokyo
    # ports:
    #   - 3306:3306

volumes:
  mysql-data:
